name: Publish Package

on:
  workflow_call:
    inputs:
      packages:
        required: true
        type: string

jobs:
  publish-package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        packages: ${{fromJson(inputs.packages)}}

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.2.1

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '21.x'
          check-latest: true
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Publish package to npm ⬆️📦
        run: |
          cd packages/${{ matrix.packages }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}