name: Scanner

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  scan-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7

      - name: Detect modified packages 📦📝
        id: detect_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          MODIFIED_PACKAGES=""
          
          for package in ./packages/*; do
            if echo "$CHANGED_FILES" | grep -q "$package"; then
              package_name=$(basename "$package")
              MODIFIED_PACKAGES="$MODIFIED_PACKAGES $package_name"
            fi
          done

          echo "Modified packages: $MODIFIED_PACKAGES"
          echo "::set-output name=packages::$MODIFIED_PACKAGES"

  trigger-package-workflows:
    needs: scan-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(steps.detect_changes.outputs.packages) }}

    steps:
      - name: Trigger package workflow
        uses: ./.github/workflows/__package.yml
        with:
          package: ${{ matrix.package }}

  trigger-docker:
    needs: [scan-packages, trigger-package-workflows]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker workflow
        uses: ./.github/workflows/__docker.yml
        with:
          pr_id: ${{ github.event.pull_request.number || 'none' }}
          github_ref: ${{ github.ref }}
